name: Download and save feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  get-files:
    name: Get files
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Get data
        run: |
          curl -o botw-switch.rss 'https://api.gamebanana.com/Rss/New?gameid=6386&itemtype=Mod'
          curl -o botw-wiiu.rss 'https://api.gamebanana.com/Rss/New?gameid=5866&itemtype=Mod'
          curl -o totk.rss 'https://api.gamebanana.com/Rss/New?gameid=7617&itemtype=Mod'
          curl -o wwhd.rss 'https://api.gamebanana.com/Rss/New?gameid=8216&itemtype=Mod'

      - name: Fix data
        run: |
          sed -i -e 's/items>$/channel>/' *.rss

      - name: Commit data
        run: |
          git config user.name "Updater"
          git config user.email "updater@gamebanana.com"
          git add .
          git commit --allow-empty -m "$(date -u)"
          git push
