name: Download and save feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  get-files:
    name: Get files
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Get data
        run: |
          FEED="https://api.gamebanana.com/Rss/New?gameid=7617&itemtype=Mod"
          curl -O "$FEED"

      - name: Commit data
        run: |
          git config user.name "Updater"
          git config user.email "updater@gamebanana.com"
          git add .
          git commit --allow-empty -m "$(date -u)"
          git push
